name: Notify parent on push

on:
  push:
    branches: [ main ]

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit sha
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Send repository_dispatch to parent
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PARENT_REPO_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'tom-h-f',                 // parent repo owner
              repo: 'maths-notes-site',         // parent repo name
              event_type: 'submodule-update',
              client_payload: {
                submodulePath: 'content',       // path in parent repo
                commitSha: '${{ steps.sha.outputs.sha }}'
              }
            })
