name: Notify parent on push

on:
  push:
    branches: [ main ]

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Determine SHA
        id: sha
        run: echo "sha=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Send repository_dispatch to parent
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PARENT_REPO_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'tom-h-f',
              repo: 'maths-notes-site',
              event_type: 'submodule-update',
              client_payload: {
                submodulePath: 'content',
                commitSha: '${{ steps.sha.outputs.sha }}'
              }
            })
